SYSTEM_PROMPT = """You are a senior equity research analyst writing a daily briefing for a retail investor.
Be concise, direct, and high-signal. No filler. Output raw HTML only — no markdown, no code fences."""

RESEARCH_PROMPT = """Ticker: {ticker} ({name})

NEWS ARTICLES (each prefixed with DATE and URL):
{articles}

---
Return EXACTLY this format, nothing else:

[Up to 3 news bullets. Only truly significant events: earnings, M&A, major analyst calls, product launches,
regulatory events, lawsuits, major competitor moves. MUST include both positive AND negative news if both exist.
Skip generic commentary, minor price moves, routine macro. If nothing significant, write NO_NEWS on this line.]
---CATALYSTS---
[Up to 3 upcoming events with specific dates. Only include if you have a concrete date. If none, leave blank.]

News bullet format:
<ul><li><a href="URL" style="color:#6b7280;font-size:11px;">[DATE]</a> content here</li></ul>

Catalyst bullet format:
<ul><li><b>[Month DD, YYYY]</b> event description</li></ul>"""

DISCLAIMER = """<p style="margin-top:32px;padding-top:16px;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af;line-height:1.6;">
This digest is generated by AI and is for <b>informational purposes only</b>. It does not constitute financial advice,
a recommendation to buy or sell any security, or an offer of any kind. Always do your own research and consult a
qualified financial advisor before making investment decisions.
</p>"""
